baseurl = "/"
languageCode = "en-GB"
title = "Konrad Zdeb's Personal Blog"
theme = "hugo-theme-cactus-plus"
googleAnalytics = "UA-129716792-1"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
# Asper the config (does not have Asian language)
hasCJKLanguage = false

[params]
    author = "Konrad Zdeb"
    description = "Personal blog on R, business intelligence, data science and statistics"
    twitter = "konradzdeb"

    enableRSS = true
    enableToc = true

    enableDisqus = false
    enableGoogleAnalytics = true

    # Provide summary
    enableSummary = true

    # Show twitter
    enableTwitterCard = true

    # show latest posts in single page
    showLatestPosts = true

    # Show nice icons
    iconFont = "mono-social"

    # Navigation links
    archive = ""


# Add additional social link entries underneath
[social]
	circletwitterbird = "https://www.twitter.com/konradzdeb"
	circlegithubalt = "https://www.github.com/konradedgar"
	circlelinkedin = "https://uk.linkedin.com/in/konradz"
	circlestackoverflow = "https://stackoverflow.com/users/1655567/konrad"
